### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by glebm**

### CODE REVIEW

**Comment by jayroh** [comment]
This commit summary made me laaauuuuugh hahahah

**Comment by glebm** [comment]
Travis takes 5 years to add MySQL v5.6 (but not to to the container distro) and botches the root user setup (https://github.com/travis-ci/travis-ci/issues/6961). Don't be like Travis. :sweat_smile: 

Trying it out with any Rails + MySQL app before doing a release would've caught this.
Good faith limit exceeded.

**Comment by jayroh** [comment]
So this begs the question - maybe time to try out circleci/codeship/etc for
some OSS stuff?

**Comment by glebm** [comment]
Yes, definitely, the next time travis breaks :+1:

**Pull request merged**
