### PR TITLE
travis: Test on Ruby 3 + Rails 6.1

### PR DESCRIPTION
**Pull request by lemingos**

### CODE REVIEW

**Comment by glebm** [comment]
> spec/gemfiles/rails_6_1.gemfile not found, cannot continue

**Comment by lemingos** [comment]
> > spec/gemfiles/rails_6_1.gemfile not found, cannot continue

Yeah, I've seen that. I've not been using Travis before. Do you think this version is not supported? 
Should I try with 6.0 ?

**Comment by glebm** [comment]
https://github.com/thredded/db_text_search/tree/master/spec/gemfiles

**Comment by glebm** [comment]
Please add rails_6_1.gemfile there
I'm not sure how well 6.0 supports ruby 3 at this point

**Comment by lemingos** [comment]
The errors are probably caused due to change in how ruby 3 handles arguments 
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

I am going to take a look later. Need to set it up locally

**Comment by glebm** [comment]
Sounds good

**Pull request merged**
